# Generated by Django 5.1.15 on 2026-03-05 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('api_key_prefix', models.CharField(blank=True, default='', max_length=8)),
                ('calls_total', models.IntegerField(default=0)),
                ('calls_generate', models.IntegerField(default=0)),
                ('calls_chat', models.IntegerField(default=0)),
                ('calls_embeddings', models.IntegerField(default=0)),
                ('calls_2xx', models.IntegerField(default=0)),
                ('calls_4xx', models.IntegerField(default=0)),
                ('calls_5xx', models.IntegerField(default=0)),
                ('avg_latency_ms', models.FloatField(default=0)),
                ('tokens_in_total', models.IntegerField(default=0)),
                ('tokens_out_total', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_aggregates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'user', 'api_key_prefix')},
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_key_prefix', models.CharField(max_length=8)),
                ('endpoint', models.CharField(max_length=200)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('status_code', models.IntegerField()),
                ('latency_ms', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('streaming', models.BooleanField(default=False)),
                ('request_size', models.IntegerField(blank=True, null=True)),
                ('response_size', models.IntegerField(blank=True, null=True)),
                ('tokens_in', models.IntegerField(blank=True, null=True)),
                ('tokens_out', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='usage_reque_user_id_f59ade_idx'), models.Index(fields=['api_key_prefix', '-timestamp'], name='usage_reque_api_key_fbf802_idx')],
            },
        ),
    ]
